version: '3'

services:
  web:
    container_name: "stupid_web"
    image: registry.cn-shenzhen.aliyuncs.com/maple007/stupid-restaurant:latest
    ports:
      - "8081:80"
    volumes:
      - ./.config/appsettings.json:/app/appsettings.json
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
  db:
    container_name: "stupid_db"
    image: "mysql:5.7"
    restart: always
    volumes:
      - ./data:/db
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: cs_hotel
      MYSQL_USER: hotel
      MYSQL_PASSWORD: password

